# Create a new user
POST http://localhost:3001/api/task/new
Content-Type: application/json

{
  "title": "Нужно починить кран и вкутить лампочки.",
  "description": "Вода капает (бесит), и темно как в ж..",
  "category": "Ремонт4",
  "price": 100,
  "dueDate": "2023-05-09",
  "image": "photo.jpg",
  "address": "ул. Улица, дом 1, к2, кв3",
  "tags": [
    "опасная",
    "страемная"
  ],
  "city": "Moscow",
  "userId": "123456"
}

###

# Get all tasks and filtres
GET http://localhost:3001/api/task?category=5&limit=2&page=3&tag=стремная

###

