# Create a new user
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "Keks",
  "email": "keks6@gmail.com",
  "city": "Moscow",
  "password": "qwerty",
  "role": "customer",
  "dateBirth": "2020-02-02"
}

###

# Get user by ID
GET http://localhost:3000/api/auth/64626979f9bc68e3cd2f35b7 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDYyNjk3OWY5YmM2OGUzY2QyZjM1YjciLCJlbWFpbCI6Imtla3M2QGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsIm5hbWUiOiJLZWtzIiwiaWF0IjoxNjg0MTcxMTcxLCJleHAiOjE2ODQxNzE3NzF9.C0P9o7NwgvgSxXZINFkbnrtKsYKhLnT3W07YSbka7JE

###

# Login user by email and password
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "keks6@gmail.com",
  "password": "qwerty"
}

###

# Get new JWT pair
POST http://localhost:3000/api/auth/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDVmYzhhZTg5OTViNDg4NzIxOTQzNDciLCJlbWFpbCI6Imtla3NAZ21haWwuY29tIiwicm9sZSI6ImN1c3RvbWVyIiwibmFtZSI6Iktla3MiLCJ0b2tlbklkIjoiYWU3MTY5ZjItODVlMS00MjcwLWEyYmItZjAzNDNjNWJlZjViIiwiaWF0IjoxNjg0MTI5MzA0LCJleHAiOjE2ODQ1NjEzMDR9.f_yI62b4DbPs1eT7swiJj9yLAuNHHkJmN8f0cFqSatI

###
