# Create a new user
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "Keks",
  "email": "keks5@gmail.com",
  "city": "Moscow",
  "password": "qwerty",
  "role": "customer",
  "dateBirth": "2020-02-02"
}

###

# Get user by ID
GET http://localhost:3000/api/auth/645fc8ae8995b48872194347 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDVmYzhhZTg5OTViNDg4NzIxOTQzNDciLCJlbWFpbCI6Imtla3NAZ21haWwuY29tIiwicm9sZSI6ImN1c3RvbWVyIiwibmFtZSI6Iktla3MiLCJpYXQiOjE2ODQwNDgxNzksImV4cCI6MTY4NDA0ODc3OX0.8TQF_h2espmw59xa5lkOWpnJ4qKqGbRqAWfDanBnZOs

###

# Login user by email and password
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "keks@gmail.com",
  "password": "qwerty"
}

###
